<?php

use Illuminate\Database\Seeder;

class DishesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {




        $platos = [
            [	'Imagen'=>'terciopelo_calabaza.png',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, QUESO AHUMADO, ACEITE DE OLIVA, MANTEQUILLA Y NATA LIQUIDA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'VELVET OF ORGANIC PUMPKIN','de'=>'SAMTIGES VOM BIO-KÜRBIS','es'=>'TERCIOPELO DE CALABAZA ECOLÓGICA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'potaje_berros.png',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, BATATA BLANCA, CILANTRO, BUBANGOS, ZANAHORIA, BERROS MANOJO, AJOS PELADOS, PIMIENTA PALMERA, GOFIO 7 CEREALES, PIMIENTOS ROJOS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TRADITIONAL WATERCRESS STEW','de'=>'TRADITIONELLER KRESSE-EINTOPF','es'=>'POTAJE DE BERROS TRADICIONAL',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'sopa_pollo.png',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, POLLO, CILANTRO, FIDEOS FINOS, ZANAHORIAS, PEREJIL, AJOS PELADOS, PIMIENTA PALMERA, HUEVOS, PIMIENTOS ROJOS.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'FINE CHICKEN STRIPES SOUP','de'=>'SUPPE MIT HÜHNERFÄDEN UND MINZE','es'=>'SOPA DE POLLO HILADO Y HIERBA HUERTO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'crematomate.png',	'Ingredientes'=>'TOMATE PARRILLA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, POLLO,CILANTRO, FIDEOS FINOS, ZANAHORIA, CILANTRO, AJOS PELADOS, PIMIENTA PALMERA, HUEVOS, PIMIENTOS ROJOS. ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BRANCH TOMATOES CREAM','de'=>'STRAUCHTOMATEN-CREME','es'=>'CREMA DE TOMATITOS DE RAMA CON CRUJIENTE DE MILLO',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'papas_bonitas.png',	'Ingredientes'=>'PAPAS BONITAS, PIMIENTA PALMERA, AJOS PELADOS, ACEITE CORRIENTE, CAYENA RAMA, COMINOS, SAL GRUESA, VINAGRE JEREZ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'“PAPAS BONITAS” MINIATURE (CANARIAN VARIETY OF POTATOES)','de'=>'KLEINE "PAPAS BONITAS" (KARTOFFELSORTE AUS TENERIFFA)','es'=>'PAPAS BONITAS MINIATURAS',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'escaldon_pescado.png',	'Ingredientes'=>'PAPAS DEL PAIS, PIMIENTA PALMERA, AJOS PELADOS, CAYENA RAMA, COMINOS, SAL GRUESA, VINAGRE JEREZ, CEBOLLAS ROJAS, PUERROS DEL PAIS, PIMIENTOS ROJOS, PAMPANO CONGELADO, GOFIO 7 CEREALES, CILANTRO',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CASSEROLE OF “FISH ESCALDÓN” (TIPICAL MIX OF GOFIO AND FISH BROTH)','de'=>'CASSEROLE VOM "FISCH ESCALDÓN" (TRADITIONELLE MISCHUNG AUS GOFIO UND FISCHFOND)','es'=>'CAZUELITA DE ESCALDÓN DE PESCADO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'delicias_crujientes.png',	'Ingredientes'=>'PAPAS DEL PAIS, PIMIENTA PALMERA, AJOS PELADOS, ACEITE DE OLIVA, CAYENA RAMA, COMINOS, SAL GRUESA, HARINA DE TRIGO, CEBOLLA ROJA, PUERROS DEL PAIS, PIMIENTOS ROJOS, HUEVAS DE CABALLA, PAN RALLADO, LECHE DE SOJA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CRUNCHY DELIGHT OF CAVIAR GOMERO','de'=>'KNUSPRIGE KÖSTLICHKEITEN AUS KAVIAR GOMERO','es'=>'DELICIAS CRUJIENTES DE CAVIAR GOMERO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'ensalada_tomate_rama.png',	'Ingredientes'=>'TOMATE EN RAMA, VINAGRE DE JEREZ, AJOS PELADOS, ACEITE DE OLIVA VIRGEN EXTRA,MIEL PALMA, COMINOS, SAL GRUESA, ALMENDRAS FILETEADAS, CABOLLA ROJA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BRANCH TOMATOES SALAD','de'=>'STRAUCHTOMATEN SALAT','es'=>'ENSALADA DE TOMATES DE RAMA',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'ensalada_queso.png',	'Ingredientes'=>'LECHUGA HOJA ROBLE, LECHUGAS PAIS, RUCULA, TOMATE CHERRY, TOMATE PARRILLA, MIEL PALMA, ACEITE EXTRA VIRGEN, ACETO BALSAMICO DUCA, ALMENDRAS FILETEADAS, QUESO BLANCO GUARAPO, CEBOLLAS ROJAS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'WARM SALAD OF MAJORERA GOAT CHEESE','de'=>'WARMER SALAT VON MAJORERA ZIEGENKÄSE','es'=>'ENSALADA TEMPLADA DE QUESO DE CABRA MAJORERA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'montaditos_batata_cherne.png',	'Ingredientes'=>'LECHUGA HOJA ROBLE, LECHUGAS PAIS, RUCULA, TOMATE CHERRY, TOMATE PARRILLA, AJOS PELADOS, ACEITE EXTRA VIRGEN, ACETO BALSAMICO DUCA, BATATA BLANCA, CILANTRO, CEBOLLA ROJA, PAMPANO CONGELADO, LIMONES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SWEET POTATO SANDWICHES WITH WRECKFISH CRUMBS 2 UNITS','de'=>'SÜßKARTOFFEL-KANAPEES MIT WRACKBARSCH BRÖSELN 2 ST','es'=>'MONTADITOS DE BATATA CON MIGAS DE CHERNE 2U',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'queso_plancha.png',	'Ingredientes'=>'QUESO AHUMADO, QUESO GOMERA CURADO CABRA Y OVEJA, QUESO BLANCO GUARAPO, MERMELADA TOMATE, CILANTRO MANOJO.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PLATE OF CANARIAN GRILLED CHEESE','de'=>'PLATTE VON KANARISCHEM GEGRILLTEN KÄSE','es'=>'PIZARRA DE QUESOS CANARIOS A LA PLANCHA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'gamba_tempura.png',	'Ingredientes'=>'LANGOSTINOS, MILLO PALOMITAS, QUESO BLANCO GUARAPO, ACEITE OLIVA, PAPAS PAIS, MANTEQUILLA, PIMIENTA PALMERA',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PRAWNS WITH PUFFED CORN TEMPURA','de'=>'GARNELEN IM PUFFMAISMANTEL','es'=>'GAMBAS EN TEMPURA DE MILLO INFLADO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'garbanzo.png',	'Ingredientes'=>'PATA CERDO, FIDEOS GRUESOS, CHORIZO CULAR ROJO, ACEITE OLIVA, PAPAS ARRUGADAS, COMINOS, PIMIENTA PALMERA, GARBANZOS, ZANAHORIAS, CALABAZA, BUBANGOS, PIMIENTO ROJO, AJOS PELADOS, COSTILLAS CUBO. ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CHICKPEAS STEW','de'=>'KICHERERBSEN EINTOPF','es'=>'RANCHO DE GARBANZOS AL COMINO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'tallarin_calamar.png',	'Ingredientes'=>'BACON, CALAMAR GRANDE, NATA LIQUIDA, CEBOLLA BLANCA, PEREJIL, ALGA NORI  ',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SAUTÉED SQUID NOODLES','de'=>'TINTENFISCH NUDELN','es'=>'TALLARINES DE CALAMAR',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'pata_asada.png',	'Ingredientes'=>'PATA CERDO, ACEITE EXTRA VIRGEN, SAL DE VINO TINTO, CEBOLLAS ROJAS, AGUACATES GRANDES, LIMONES.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CANARIAN ROASTED PORK LEG','de'=>'GEBRATENE KANARISCHE SCHWEINEKEULE','es'=>'PATA ASADA CANARIA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'flor_calabaza.png',	'Ingredientes'=>'HARINA DE TRIGO, AZUCAR, CALABAZA, LEVADURA, YOGUR DE SOJA, HORTELANA MANOJO, BUBANGOS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PUMPKIN FLOWER FROM OUR GARDEN IN CRISPY TEMPURA','de'=>'KÜRBISBLÜTE AUS UNSEREM GARTEN IN KNUSPRIGEM TEMPURAMANTEL','es'=>'FLOR DE CALABAZA DE NUESTRA HUERTA EN TEMPURA CRUJIENTE',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'pulpo.png',	'Ingredientes'=>'PULPO, SAL GRUESA, ACEITE OLIVA, SAL MALDON, PIMENTON DULCE, PEREJIL, BATATA BLANCA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GRILLED OCTOPUS TENTACLES','de'=>'GEGRILLTE TINTENFISCHTENTAKEL','es'=>'REJOS DE PULPO A LA PARRILLA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'lapas.png',	'Ingredientes'=>'LAPAS, CILANTRO, PIMIENTOS VERDES, LIMONES, ACEITE CORRIENTE, SAL FINA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'LIMPETS GRILLED ON BRAZIER','de'=>'NAPFSCHNECKEN','es'=>'LAPAS ASADAS EN BRASERO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'langostino.png',	'Ingredientes'=>'LANGOSTINOS, ACEITE OLIVA, TOMATE CHERRY, AJETES BANDEJA, BATATA BLANCA, CILANTRO, PIMIENTOS VERDES',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PRAWNS IN MALVASIA SAUCE','de'=>'GARNELEN IN MALVASIA-SAUCE','es'=>'LANGOSTINOS EN SALSA DE MALVASÍA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'cherne.png',	'Ingredientes'=>'CHERNE FRESCO, CILANTRO, PIMIENTOS VERDES, PAPAS NEGRAS, ACEITE CORRIENTE, SAL FINA, PIMIENTA PALMERA, PIMIENTOS ROJOS, PIMENTON DULCE, COMINOS, CAYENA RAMA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'ROASTED WRECKFISH LOIN','de'=>'KNUSPRIG GEBRATENES WRACKBARSCH-FILET','es'=>'LOMO DE CHERNE ASADO CON CRUJIENTE DE SU PIEL',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'chicharro.png',	'Ingredientes'=>'CABALLAS CONGELADAS, CILANTRO, CEBOLLA BLANCA, BATATA BLANCA, ACEITE CORRIENTE, SAL FINA, PIMIENTA PALMERA, PIMIENTOS ROJOS, PIMENTON DULCE, COMINOS, CAYENA RAMA, MAHONESA, PIMIENTOS VERDES, VINAGRE DE JEREZ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'FRIED HORSE MACKEREL DELIGHTS','de'=>'KÖSTLICHKEITEN VOM GEBRATENEN STÖCKER','es'=>'DELICIAS DE CHICHARRO FRITAS',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'bacalao.png',	'Ingredientes'=>'LOMO BACALAO, ACEITE OLIVA,TOMATE PARRILLA, AJOS PELADOS, CEBOLLA BLANCA, PIMIENTOS ROJOS, PIMIENTOS VERDES, ACEITUNAS DESHUESADAS, ALMENDRAS FILETEADAS. ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'COD CONFIT IN CANARIAN EVOO*','de'=>'KABELJAU-CONFIT IN KANARISCHEM NOE*','es'=>'BACALAO CONFITADO EN AOVE CANARIO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'atun.png',	'Ingredientes'=>'LOMO ATUN FRESCO, ACEITE OLIVA, PUERROS PAIS, AJOS PELADOS, BATATA BLANCA, VINAGRE SIDRA, SALSA SOJA, AGUACATES GRANDES, LIMONES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'MARINATED BONITO FISH CHUNK','de'=>'MARINIERTES BONITO FISCHSTÜCK','es'=>'TACO DE BONITO MARINADO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'sama.png',	'Ingredientes'=>'SAMA FRESCA, ACEITE OLIVA, PUERROS PAIS, AJOS PELADOS, PIMIENTA PALMERA, VINAGRE SIDRA, PIMIENTOS VERDES, PIMIENTOS ROJOS, ERIZOS DE MAR FRESCOS.',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GRILLED BLUE SPOTTED SEABREAM FILLET','de'=>'GEBRATENES GOLDBRASSEN FILET','es'=>'FILETE DE SAMA DORADO EN PLANCHA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'timbal_costillas.png',	'Ingredientes'=>'COSTILLAS CUBO, ACEITE OLIVA, CILANTRO, AJOS PELADOS, PIMIENTA PALMERA, VINAGRE SIDRA, PIMIENTOS VERDES, PIMIENTOS ROJOS, PAPAS PAIS, PIÑA MILLO FRESCA, MILLO DULCE LATA, NATA LIQUIDA, GELATINA LAMINA.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'RIBS TIMBALE','de'=>'RIBCHEN TIMBAL','es'=>'TIMBAL DE COSTILLAS CON PAPAS Y MOJO DE CILANTRO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'legumeat.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'Sí',],	'translate'=>['en'=>'TIMBALE OF LEGUMEAT (MEAT SUBSTITUTE MADE WITH LEGUMES)','de'=>'TIMBAL VON LEGUMEAT (FLEISCHERSATZ MIT HÜLSENFRÜCHTEN)','es'=>'TIMBAL DE LEGUMEAT CON PAPAS Y MOJO DE CILANTRO',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'conejo.png',	'Ingredientes'=>'CONEJO, ACEITE OLIVA, CILANTRO, AJOS PELADOS, PIMIENTA PALMERA, VINAGRE SIDRA, PIMIENTOS VERDES, PIMIENTOS ROJOS, PAPAS PAIS, PEREJIL, ALMENDRAS FILETEADAS, ZANAHORIAS, XANTANA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PRESSED RABBIT MEAT IN SALMOREJO SAUCE','de'=>'GEPRESSTES KANINCHENFLEISCH IN SALMOREJO SAUCE','es'=>'PRENSADO DE CONEJO EN SALMOREJO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'medallon_buey.png',	'Ingredientes'=>'SOLOMILLO, ACEITE OLIVA, CALABAZA, AJOS PELADOS, VINO TINTO, VINAGRE SIDRA, PIMIENTOS ROJOS, PIMIENTOS VERDES, PAPAS PAIS, PEREJIL, PIPAS DE CALABAZA, AZUCAR, XANTANA.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BEEF MEDALLIONS FLAMBÉ WITH HONEY RUM','de'=>'RINDERMEDAILLONS MIT HONIG RUM FLAMBIERT','es'=>'MEDALLONES DE BUEY FLAMBEADOS CON RON MIEL',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'cochino_guarapo.png',	'Ingredientes'=>'COSTILLAR DE CERDO FRESCO, PAPAS CONSUMO, AJOS PELADOS, NATA LIQUIDA, MIEL PALMA, MANTEQUILLA, QUESO AHUMADO CABRA, ROMERO, NARANJAS ZUMO',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GRILLED CANARIAN PORK RIBS COATED WITH GUARAPO','de'=>'GEGRILLTE SCHWEINE-RIPPCHEN MIT GUARAPO BESTRICHEN','es'=>'COSTILLAS DE COCHINO A LA PARRILLA PINTADAS CON GUARAPO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'pollo.png',	'Ingredientes'=>'MUSLOS DE POLLO DESHUESADOS, PAPAS PAIS, AJOS PELADOS, PIMIENTA PALMERA, ACEITE CORRIENTE, ALMENDRAS FILETEADAS, PIMIENTOS ROJOS, CILANTRO, PEREJIL, PIMENTON DULCE.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'POULTRY CHICKEN BREAST COATED WITH MOJO SAUCE','de'=>'BRUST VOM FREILANDHUHN MIT MOJO-SAUCE ÜBERZOGEN','es'=>'PECHUGA DE POLLO DE CORRAL EMBARRADA EN MOJO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'secreto.png',	'Ingredientes'=>'PRESA DE CERDO IBERICA, PAPAS NEGRAS, AJOS PELADOS, PIMIENTA PALMERA, ACEITE CORRIENTE, ALMENDRAS FILETEADAS, PIMIENTOS ROJOS, CILANTRO, PEREJIL, PIMENTON DULCE',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'“SECRETO IBÉRICO” (SPECIAL PORK CUT)','de'=>'SECRETO IBÉRICO (SPEZIELLES STÜCK VOM SCHWEIN)','es'=>'SECRETO DE CERDO A LA PARRILLA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'carrillada.png',	'Ingredientes'=>'CARRILLADA TERNERA, PAPAS BONITAS, AJOS PELADOS, PIMIENTA PALMERA, ACEITE CORRIENTE, VINO TINTO, CEBOLLA BLANCA, ZANAHORIAS, PUERROS PAIS, PIMENTON DULCE, NATA LIQUIDA, MANTEQUILLA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BEEF CHEEKS WITH LISTÁN NEGRO WINE REDUCTION','de'=>'RINDERBÄCKCHEN MIT LISTÁN NEGRO WEINREDUKTION','es'=>'CARRILLERAS DE BUEY CON REDUCCIÓN DE VINO LISTÁN NEGRO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'solomillo_cordero.png',	'Ingredientes'=>'SOLOMILLO, MIEL PALMA, MANTEQUILLA, ROMERO, VINAGRE, PIMIENTA NEGRA, BATATA BLANCA, ACEITE CORRIENTE, SAL FINA, MANGO CONGELADO',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'LAMB TENDERLOIN COATED WITH PALM HONEY','de'=>'LAMMBRATEN MIT PALMENHONIG BESCHICHTET','es'=>'SOLOMILLO DE CORDERO LACADO CON MIEL DE PALMA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'bichillo_cochino.png',	'Ingredientes'=>'SOLOMILLO IBERICO BLAZQUEZ, BACON CORTADO, PIÑA TROPICAL, AZUCAR, VINAGRE, CLAVO, BATATA BLANCA, ACEITE CORRIENTE, SAL FINA, AGUACATES GRANDES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BLACK PORK TENDERLOIN WRAPPED IN CRISPY BACON','de'=>'SCHWARZES SCHWEINEFILET IN KNUSPRIGEM SPECKMANTEL','es'=>'BICHILLO DE COCHINO NEGRO ALBARDADO EN PANCETA CRUJIENTE',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'solomillo.png',	'Ingredientes'=>'SOLOMILLO, MANZANA RED CHIFF, MANTEQUILLA, TOMILLO, SAL MALDON, PIMIENTA NEGRA, PAPAS, ACEITE CORRIENTE, SAL FINA, PURE DE MARACUYA SICOLY, AZUCAR',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BEEF TENDERLOIN GLAZED WITH PASSION FRUIT SAUCE','de'=>'RINDERFILET GLASIERT MIT PASSIONSFRUCHTSAUCE','es'=>'SOLOMILLO DE BUEY GLASEADO CON SALSA DE PARCHITA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'mouse_gofio.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GOFIO MOUSSE','de'=>'GOFIO-MOUSSE','es'=>'MOUSSE DE GOFIO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'quesillo_gomero.png',	'Ingredientes'=>'AZUCAR, LECHE LIQUIDA, LECHE CONDENSADA, HUEVOS, MIEL DE PALMA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TRADITIONAL QUESILLO GOMERO (MILK DESSERT)','de'=>'TRADITIONELLES QUESILLO GOMERO (MILCHDESSERT)','es'=>'QUESILLO TRADICIONAL GOMERO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'brocheta_papaya.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SKEWER WITH PAPAYA FROM LA GOMERA AND PINEAPPLE FROM EL HIERRO','de'=>'SPIEß MIT PAPAYA VON LA GOMERA UND ANANAS VON EL HIERRO','es'=>'BROCHETA DE PAPAYA GOMERA Y PIÑA HERREÑA',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'bombon_guayaba.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GUAVA AND BLACK CHOCOLATE BONBON','de'=>'BONBON AUS GUAVA UND SCHWARZER SCHOKOLADE','es'=>'BOMBÓN DE GUAYABA Y CHOCOLATE NEGRO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'helado_ron.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CINNAMON AND HONEY RUM ICE CREAM','de'=>'EIS AUS ZIMT UND HONIG RUM','es'=>'HELADO DE CANELA Y RON MIEL',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'pastel_mango.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'MANGO CAKE','de'=>'MANGO-TORTE','es'=>'PASTEL DE MANGO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'tarta_3leches.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CAKE “3 LECHES” (3 TYPES OF MILK)','de'=>'KUCHEN "3 LECHES" (3 ARTEN VON MILCH)','es'=>'TARTA DE TRES LECHES',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'degustacion.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TASTING SELECTION OF CANARIAN DESSERTS','de'=>'VERKOSTUNG EINER AUSWAHL KANARISCHER DESSERTS','es'=>'DEGUSTACIÓN DE DULCES CANARIOS',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
															
															
															
[	'Imagen'=>'',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, BATATA BLANCA, CILANTRO, BUBANGOS, ZANAHORIA, BERROS MANOJO, AJOS PELADOS, PIMIENTA PALMERA, GOFIO 7 CEREALES, PIMIENTOS ROJOS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TRADITIONAL WATERCRESS STEW SERVED WITH GOFIO GOMERO FROM 7 CEREALS, OR GLUTEN FREE FROM CORN','de'=>'TRADITIONELLER KRESSE-EINTOPF SERVIERT MIT GOFIO GOMERO AUS 7 GETREIDEN ODER GLUTENFREI AUS MAIS','es'=>'POTAJE DE BERROS TRADICIONAL SERVIDO CON GOFIO GOMERO DE 7 CEREALES O DE MILLO SIN GLUTEN',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'TOMATE EN RAMA, VINAGRE DE JEREZ, AJOS PELADOS, ACEITE DE OLIVA VIRGEN EXTRA,MIEL PALMA, COMINOS, SAL GRUESA, ALMENDRAS FILETEADAS, CABOLLA ROJA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BRANCH TOMATOES SALAD WITH MACHO VINEGAR DRESSING, PALM HONEY, ALMONDS AND ONION FLOWER','de'=>'STRAUCHTOMATEN SALAT MIT „MACHO“ ESSIG DRESSING, PALM HONIG, MANDELN UND ZWIEBELBLUME','es'=>'ENSALADA DE TOMATES DE RAMA CON ALIÑO DE VINAGRE MACHO, MIEL DE PALMA, ALMENDRAS Y FLOR DE CEBOLLA',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'HARINA DE TRIGO, AZUCAR, CALABAZA, LEVADURA, YOGUR DE SOJA, HORTELANA MANOJO, BUBANGOS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PUMPKIN FLOWER FROM OUR GARDEN IN CRISPY TEMPURA WITH SWEET SAUCE OF SOY YOGURT AND SPEARMINT','de'=>'KÜRBISBLÜTE AUS UNSEREM GARTEN IN KNUSPRIGEM TEMPURAMANTEL MIT SÜßER SOßE VON SOJAJOGHURT UND MINZE','es'=>'FLOR DE CALABAZA DE NUESTRA HUERTA EN TEMPURA CRUJIENTE CON SALSA DULCE DE YOGURT DE SOJA Y HIERBABUENA',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'RUSSET APPLE SORBET','de'=>'RENETTE APFEL SORBET','es'=>'SORBETE DE MANZANA REINETA',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'Sí',],	'translate'=>['en'=>'TIMBALE OF LEGUMEAT (MEAT SUBSTITUTE MADE WITH LEGUMES) WITH POTATOES AND CORIANDER MOJO SAUCE ON CORN MOUSSE','de'=>'TIMBAL VON LEGUMEAT (FLEISCHERSATZ MIT HÜLSENFRÜCHTEN) MIT KARTOFFELN UND KORIANDER-MOJO SAUCE AUF MAIS MOUSSE','es'=>'TIMBAL DE LEGUMEAT CON PAPAS Y MOJO DE CILANTRO SOBRE MOUSSE DE MILLO',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SKEWER WITH PAPAYA FROM LA GOMERA AND PINEAPPLE FROM EL HIERRO ON ORANGE SYRUP AND STAR ANISE','de'=>'SPIEß MIT PAPAYA VON LA GOMERA UND ANANAS VON EL HIERRO AUF ORANGENSIRUP UND STERNANIS','es'=>'BROCHETA DE PAPAYA GOMERA Y PIÑA HERREÑA CON ALMIBAR DE NARANJA Y ANÍS ESTRELLADO',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
															
[	'Imagen'=>'',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, QUESO AHUMADO, ACEITE DE OLIVA, MANTEQUILLA Y NATA LIQUIDA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'VELVET OF ORGANIC PUMPKIN WITH SURPRISE PIECE OF SMOKED GOMERO CHEESE','de'=>'SAMTIGES VOM BIO-KÜRBIS MIT ÜBERRASCHUNGSSTÜCK GERÄUCHERTEM GOMERO KÄSE','es'=>'TERCIOPELO DE CALABAZA ECOLÓGICA CON TACO SORPRESA DE QUESO GOMERO AHUMADO',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'LANGOSTINOS, MILLO PALOMITAS, QUESO BLANCO GUARAPO, ACEITE OLIVA, PAPAS PAIS, MANTEQUILLA, PIMIENTA PALMERA',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PRAWNS WITH PUFFED CORN TEMPURA ON BLACK POTATOES FROTH WITH BLACK PEPPER OIL FROM LA PALMA','de'=>'GARNELEN IM PUFFMAISMANTEL AUF SCHWARZEM KARTOFFELSCHAUM MIT PFEFFERÖL VON LA PALMA','es'=>'GAMBAS EN TEMPURA DE MILLO INFLADO SOBRE ESPUMA DE PAPAS NEGRAS Y ACEITE DE PIMIENTA PALMERA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'LOMO ATUN FRESCO, ACEITE OLIVA, PUERROS PAIS, AJOS PELADOS, BATATA BLANCA, VINAGRE SIDRA, SALSA SOJA, AGUACATES GRANDES, LIMONES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'MARINATED BONITO FISH CHUNK ON SOFT AVOCADO CREAM, FRIED LEEK AND SWEET POTATO CHIPS','de'=>'MARINIERTES BONITO FISCHSTÜCK AUF SANFTER AVOCADO-CREME, GEBRATENEM LAUCH UND UND SÜßKARTOFFEL-CHIPS','es'=>'TACO DE BONITO MARINADO SOBRE CREMA SUAVE DE AGUACATE, PUERRO FRITO Y CHIPS DE BATATA',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'RUSSET APPLE SORBET','de'=>'RENETTE APFEL SORBET','es'=>'SORBETE DE MANZANA REINETA',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'',	'Ingredientes'=>'SOLOMILLO, ACEITE OLIVA, CALABAZA, AJOS PELADOS, VINO TINTO, VINAGRE SIDRA, PIMIENTOS ROJOS, PIMIENTOS VERDES, PAPAS PAIS, PEREJIL, PIPAS DE CALABAZA, AZUCAR, XANTANA.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BEEF MEDALLIONS FLAMBÉ WITH HONEY RUM ACCOMPANIED WITH MASHED PUMPKIN AND ITS ROASTED SEEDS','de'=>'RINDERMEDAILLONS MIT HONIG RUM FLAMBIERT, BEGLEITET VON KÜRBISPÜREE UND GERÖSTETEN KÜRBISSAMEN','es'=>'MEDALLONES DE BUEY FLAMBEADOS CON RON MIEL ACOMPAÑADOS DE PURÉ DE CALABAZA Y SUS PIPAS TOSTADAS',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GOFIO MOUSSE WITH CRISPY ALMONDS','de'=>'GOFIO-MOUSSE MIT KNUSPRIGEN MANDELN','es'=>'MOUSSE DE GOFIO CON CRUJIENTE DE ALMENDRAS',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
															
[	'Imagen'=>'',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, BATATA BLANCA, CILANTRO, BUBANGOS, ZANAHORIA, BERROS MANOJO, AJOS PELADOS, PIMIENTA PALMERA, GOFIO 7 CEREALES, PIMIENTOS ROJOS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TRADITIONAL WATERCRESS STEW SERVED WITH GOFIO GOMERO FROM 7 CEREALS, OR GLUTEN FREE FROM CORN','de'=>'TRADITIONELLER KRESSE-EINTOPF SERVIERT MIT GOFIO GOMERO AUS 7 GETREIDEN ODER GLUTENFREI AUS MAIS','es'=>'POTAJE DE BERROS TRADICIONAL SERVIDO CON GOFIO GOMERO DE 7 CEREALES O DE MILLO SIN GLUTEN',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'LECHUGA HOJA ROBLE, LECHUGAS PAIS, RUCULA, TOMATE CHERRY, TOMATE PARRILLA, MIEL PALMA, ACEITE EXTRA VIRGEN, ACETO BALSAMICO DUCA, ALMENDRAS FILETEADAS, QUESO BLANCO GUARAPO, CEBOLLAS ROJAS',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'WARM SALAD OF MAJORERA GOAT CHEESE','de'=>'WARMER SALAT VON MAJORERA ZIEGENKÄSE','es'=>'ENSALADA TEMPLADA DE QUESO DE CABRA MAJORERA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'CHERNE FRESCO, CILANTRO, PIMIENTOS VERDES, PAPAS NEGRAS, ACEITE CORRIENTE, SAL FINA, PIMIENTA PALMERA, PIMIENTOS ROJOS, PIMENTON DULCE, COMINOS, CAYENA RAMA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'ROASTED WRECKFISH LOIN','de'=>'KNUSPRIG GEBRATENES WRACKBARSCH-FILET','es'=>'LOMO DE CHERNE ASADO CON CRUJIENTE DE SU PIEL',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CITRUS SORBET WITH SPEARMINT','de'=>'ZITRONEN SORBET MIT MINZE','es'=>'SORBETE DE CÍTRICO CON HIERBABUENA',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
[	'Imagen'=>'',	'Ingredientes'=>'COSTILLAS CUBO, ACEITE OLIVA, CILANTRO, AJOS PELADOS, PIMIENTA PALMERA, VINAGRE SIDRA, PIMIENTOS VERDES, PIMIENTOS ROJOS, PAPAS PAIS, PIÑA MILLO FRESCA, MILLO DULCE LATA, NATA LIQUIDA, GELATINA LAMINA.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'RIBS TIMBALE','de'=>'RIBCHEN TIMBAL','es'=>'TIMBAL DE COSTILLAS CON PAPAS Y MOJO DE CILANTRO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'AZUCAR, LECHE LIQUIDA, LECHE CONDENSADA, HUEVOS, MIEL DE PALMA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'TRADITIONAL QUESILLO GOMERO (MILK DESSERT)','de'=>'TRADITIONELLES QUESILLO GOMERO (MILCHDESSERT)','es'=>'QUESILLO TRADICIONAL GOMERO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
															
[	'Imagen'=>'',	'Ingredientes'=>'CALABAZA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, POLLO, CILANTRO, FIDEOS FINOS, ZANAHORIAS, PEREJIL, AJOS PELADOS, PIMIENTA PALMERA, HUEVOS, PIMIENTOS ROJOS.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'FINE CHICKEN STRIPES SOUP','de'=>'SUPPE MIT HÜHNERFÄDEN UND MINZE','es'=>'SOPA DE POLLO HILADO Y HIERBA HUERTO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'LECHUGA HOJA ROBLE, LECHUGAS PAIS, RUCULA, TOMATE CHERRY, TOMATE PARRILLA, AJOS PELADOS, ACEITE EXTRA VIRGEN, ACETO BALSAMICO DUCA, BATATA BLANCA, CILANTRO, CEBOLLA ROJA, PAMPANO CONGELADO, LIMONES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SWEET POTATO SANDWICHES WITH WRECKFISH CRUMBS 2 UNITS','de'=>'SÜßKARTOFFEL-KANAPEES MIT WRACKBARSCH BRÖSELN 2 ST','es'=>'MONTADITOS DE BATATA CON MIGAS DE CHERNE 2U',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'PULPO, SAL GRUESA, ACEITE OLIVA, SAL MALDON, PIMENTON DULCE, PEREJIL, BATATA BLANCA',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'GRILLED OCTOPUS TENTACLES','de'=>'GEGRILLTE TINTENFISCHTENTAKEL','es'=>'REJOS DE PULPO A LA PARRILLA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'PASSION FRUIT SORBET','de'=>'MARACUJA SORBET','es'=>'SORBETE DE PARCHITA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'Sí',],									],
[	'Imagen'=>'',	'Ingredientes'=>'SOLOMILLO IBERICO BLAZQUEZ, BACON CORTADO, PIÑA TROPICAL, AZUCAR, VINAGRE, CLAVO, BATATA BLANCA, ACEITE CORRIENTE, SAL FINA, AGUACATES GRANDES',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BLACK PORK TENDERLOIN WRAPPED IN CRISPY BACON','de'=>'SCHWARZES SCHWEINEFILET IN KNUSPRIGEM SPECKMANTEL','es'=>'BICHILLO DE COCHINO NEGRO ALBARDADO EN PANCETA CRUJIENTE',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'CAKE “3 LECHES” (3 TYPES OF MILK)','de'=>'KUCHEN "3 LECHES" (3 ARTEN VON MILCH)','es'=>'TARTA DE TRES LECHES',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
															
[	'Imagen'=>'',	'Ingredientes'=>'TOMATE PARRILLA, CEBOLLA BLANCA, PUERROS DEL PAIS, PAPAS DEL PAIS, PIÑA MILLO FRESCA, ACEITE DE OLIVA, POLLO,CILANTRO, FIDEOS FINOS, ZANAHORIA, CILANTRO, AJOS PELADOS, PIMIENTA PALMERA, HUEVOS, PIMIENTOS ROJOS. ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'BRANCH TOMATOES CREAM','de'=>'STRAUCHTOMATEN-CREME','es'=>'CREMA DE TOMATITOS DE RAMA CON CRUJIENTE DE MILLO',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'BACON, CALAMAR GRANDE, NATA LIQUIDA, CEBOLLA BLANCA, PEREJIL, ALGA NORI  ',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SAUTÉED SQUID NOODLES','de'=>'TINTENFISCH NUDELN','es'=>'TALLARINES DE CALAMAR',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'CABALLAS CONGELADAS, CILANTRO, CEBOLLA BLANCA, BATATA BLANCA, ACEITE CORRIENTE, SAL FINA, PIMIENTA PALMERA, PIMIENTOS ROJOS, PIMENTON DULCE, COMINOS, CAYENA RAMA, MAHONESA, PIMIENTOS VERDES, VINAGRE DE JEREZ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'FRIED HORSE MACKEREL DELIGHTS','de'=>'KÖSTLICHKEITEN VOM GEBRATENEN STÖCKER','es'=>'DELICIAS DE CHICHARRO FRITAS',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'SORBET AUS ANANAS VON EL HIERRO','de'=>'SORBET OF PINEAPPLE FROM EL HIERRO','es'=>'SORBETE DE PIÑA HERREÑA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'Sí',],									],
[	'Imagen'=>'',	'Ingredientes'=>'PRESA DE CERDO IBERICA, PAPAS NEGRAS, AJOS PELADOS, PIMIENTA PALMERA, ACEITE CORRIENTE, ALMENDRAS FILETEADAS, PIMIENTOS ROJOS, CILANTRO, PEREJIL, PIMENTON DULCE',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'“SECRETO IBÉRICO” (SPECIAL PORK CUT)','de'=>'SECRETO IBÉRICO (SPEZIELLES STÜCK VOM SCHWEIN)','es'=>'SECRETO DE CERDO A LA PARRILLA',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
[	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'MANGO CAKE','de'=>'MANGO-TORTE','es'=>'PASTEL DE MANGO',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
        ];

        $langs =  DB::table('languages')->get();

        foreach($platos as $plato){

            $dishId = DB::table('dishes')->insertGetId([
                "ingredients"=> $plato['Ingredientes'],
                "image"=> trim($plato['Imagen'], " \t\n\r"),
                "active"=> 1,
            ]);

            foreach ($langs as $lan) {
                DB::table('dishes_translations')->insert(
                    [
                        'id_dish' => $dishId,
                        'id_language' => $lan->id,
                        'name' => $plato['translate'][$lan->code],
                        'description' => '',
                    ]
                );
            }
            
            foreach( $plato['allergens'] as $key => $value){
                if( $value == 'Sí' ){
                    $id_allergen =  DB::table('allergens_translations')->where('name', $key)->first()->id_allergen;
                   
                    try{    
                        DB::table('allergens_dishes')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_allergen' => $id_allergen
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($plato);
                    }
                }
            }

            foreach( $plato['foodTypes'] as $key => $value){
                if( $value == 'Sí' ){
                    $id_food_type = DB::table('food_types_translations')->where('name', $key)->first()->id_food_type ;
                    try{
                        DB::table('dishes_food_types')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_food_type' => $id_food_type,
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($plato);
                    }
                }
            }

            foreach( $plato['categories'] as $key => $value){
                if( $value == 'Sí' ){
                    $id_category = DB::table('categories_translations')->where('name', $key)->first()->id_category;
                    try{
                        DB::table('categories_dishes')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_category' => $id_category
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($plato);
                    }
                }
            }

        }



        // $cant = 80;

        // for ($i = 0 ; $i < $cant ; $i++){
        //     DB::table('dishes')->insert([
        //         'ingredients' => 'ingredients_:' . $i. str_random(15),
        //         'active'=> TRUE,
        //         'image'=>'',
        //     ]);
        // }

        // for ($i = 0 ; $i < $cant ; $i++) {
        //     foreach ($lang as $lan) {
        //         DB::table('dishes_translations')->insert([
        //             [
        //                 'id_dish' => $i+1,
        //                 'id_language' => $lan->id,
        //                 'name' =>$lan->code .'_name' . ($i+1),
        //                 'description' =>$lan->code .' description' . ($i+1)
        //             ]
        //         ]);
        //     }
        // }

    }
}
