<?php

use Illuminate\Database\Seeder;

class DishesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $platos = [
															
            [	'Imagen'=>'jamon.png',	'Ingredientes'=>'Jamón bellota, tomate parrilla, aceilte extra virgen, sal maldon, pimienta negra molida, ajos pelados, chapata tradición',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Iberian ham, hand cut with thin bread and tomatoes in EVOO*','de'=>'Iberischer “Bellota” Schinken von Hand geschnitten mit dünnes Brot und Tomate in NOE*','es'=>'Jamón Ibérico de bellota cortado a mano, con pan fino y tomate en AOVE',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'ibericos.png',	'Ingredientes'=>'Chorizo ibérico, salchichon ibérico, lomo ibérico, jamón bellota, tomate parrilla, sal maldon, pimienta negra molida, aceite virgen extra, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of Iberian cold cut with rustic bread','de'=>'Auswahl an iberischem Aufschnitt mit rustikalem Brot','es'=>'Selección de embutidos ibéricos con pan rústico',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'queso.png',	'Ingredientes'=>'Queso artesano blanco cuña. Queso artesano especial cuña, queso artesano gofio cuña, queso artesano rojo cuña, mermelada calabaza, mermelada de higo negro con nuez, mermelada castaña vainilla, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of goat and sheep cheese with rustic bread. (Cheese cream tipical from La Gomera)','de'=>'Auswahl an Ziegen‐und Schafskäse mit rustikalem Brot. Manchego Käse, geräucherter Gomero Käse, Majorero Käse, Palmero Käse, Almogrote Gomero (typischer Käse Aufstrich)','es'=>'Selección de quesos de cabra y oveja con pan rústico. (Queso Manchego, Queso Gomero ahumado, Queso Majorero, Queso Palmero, Almogrote Gomero)',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'salmorejo.png',	'Ingredientes'=>'Tomate parrilla, ajos pelados, aguacates grandes, borraja fresca, agua, aceite oliva, vinagre jerez, sal fina, jamon bellota.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Salmorejo of organic tomato in EVOO*, slices of Iberian ham and avocado','de'=>'Salmorejo aus Bio‐Tomaten mit NOE*, Scheiben vom iberischen Schinken und Avocado','es'=>'Salmorejo de tomate ecológico con AOVE, lascas de jamón ibérico y aguacate',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'bacalao.png',	'Ingredientes'=>'lomo bacalao, ajos pelados, pimientos rojos, tomate ensalada, aceite oliva, aceite virgen extra, vinagre jerez, sal maldon, aceitunas negras, brotes de sakura mix',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Cod Confit salad on tomato slices and back olive powder','de'=>'Kabeljau Confit Salat auf Scheibchen von Tomaten und Pulver schwarzer Oliven','es'=>'Ensalada de Bacalao confitado sobre láminas de tomate y polvo de aceitunas negras',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'ensaladilla_rusa.png',	'Ingredientes'=>'papas, cebollas blancas, perejil, huevos, gambon, mahonesa, aceitunas deshuesada , salsa tomate',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Russian salad with big shrimps and green olives','de'=>'Russischer Salat mit Riesengarnelen und grünen Oliven','es'=>'Ensaladilla Rusa con gambones y olivas verdes.',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'ens_aguacate_mango.png',	'Ingredientes'=>'pure de maracuya, aguacates grandes, lechuga hoja roble, aceite oliva, aceite oliva virgen extra, vinagre jerez, sal maldon, cebollas rojas, brotes de sakura mix, mango congelado',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Salad of tender sprouts, avocado and mango with passion fruit vinaigrette','de'=>'Salat aus jungen Sprossen, Avocado und Mango mit Passionsfrucht Vinaigrette','es'=>'Ensalada de brotes tiernos, aguacate y mango con vinagreta de maracuyá',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'puerros.png',	'Ingredientes'=>'puerros pais, ajos pelados, perejil, tomate ensalada, aceite oliva, aceite oliva virgen extra ajo, vinagre jerez, sal maldon, pimienta negra grano, brotes de sakura mix, piñones',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Caramelized leeks with fruits trail vanaigrette','de'=>'Karamellisierter Porree mit Vinaigrette aus Trockenfrüchten','es'=>'Puerros caramelizados con vinagreta de frutos secos',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'canelon_remolacha.png',	'Ingredientes'=>'laminas de remolacha, cebolla blanca, zanahorias, ajos pelados, puerros del pais, brote variados, brotes variados, lomo fresco atun, mahonesa, jengibre, yuca, batata blanca, vinagre balsamico, azucar',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Beetroot cannelloni stuffed with pickled tuna and tender sprouts on reduction of Modena','de'=>'Rote Bete‐Cannelloni gefüllt mit eingelegtem Thunfisch und zarten Sprossen an einer Modena‐Reduktion','es'=>'Canelón de remolacha relleno de atún escabechado y brotes tiernos con reducción de Módena',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'pimientos.png',	'Ingredientes'=>'aceite de olvia, sal maldon, pimientos del padron',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Padrón peppers','de'=>'Paprika aus Padrón','es'=>'Pimientos de Padrón',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'huevo_pintxo.png',	'Ingredientes'=>'pinxto de huevo frito, grasa vegetal lata ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Egg yolk wrapped in Iberian bacon and potato 2units','de'=>'Eigelb mit iberischem Schinkenspeck und Kartoffeln umwickelt 2 St','es'=>'Pincho de huevo, panceta ibérica y patata 2u.',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'huevo_trufa_pintxo.png',	'Ingredientes'=>'pinxto de huevo frito con trufa',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Egg yolk wrapped in potato and black truffle 2 units','de'=>'Eigelb mit Kartoffeln und schwarzem Trüffel umwickelt 2 St.','es'=>'Pincho de huevo con patata y trufa negra 2 u.',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'tortilla.png',	'Ingredientes'=>'mini torrilla de patata, aceite extra virgen, brotes de sakura ',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Mini gourmet potato tortilla','de'=>'Mini Gourmet‐Kartoffel‐Tortilla','es'=>'Mini tortilla de patata gourmet',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'croquetas.png',	'Ingredientes'=>'croqueta de bacalao cebolla caramelizada, croqueta jamon iberico pan crujiente, croquetas bacon y platano koama, croquetas de queso azul nueces, croquetas parmesano y tomate, corquetas de boletus con escamas',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of 6 croquettes (1 unit of each flavour) (Iberian ham with crusty bread, blue cheese and walnuts, Parmesan with tomato, cod with caramelized onions, Boletus with potato flakes and banana with bacon)','de'=>'Zusammenstellung verschiedener Kroketten 6 St. (Iberischer Schinken mit knusprigem Brot, Blauschimmelkäse und Nüssen, Parmesan mit Tomate, Kabeljau mit karamellisierten Zwiebeln, Steinpilz mit Kartoffelflocken und Banane mit Speck)','es'=>'Surtido de croquetas 6u. (1u de cada sabor) (Jamón Ibérico con pan crujiente, Queso azul y nueces, Parmesano con tomate, Bacalao con cebolla caramelizada, Boletus con escamas de patata y Plátano con Bacon',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'berenjenas.png',	'Ingredientes'=>'berenjema, aceite naranja, aceite oliva, miel abeja, romero, brotes variados',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Fried eggplants with orange, honey and rosemary vinaigrette','de'=>'Frittierte Auberginen mit Orangen‐Vinaigrette, Honig und Rosmarin','es'=>'Berenjenas fritas con vinagreta de naranja, miel de abeja y romero',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'coca_foie.png',	'Ingredientes'=>'higado de pato fresco, pedro jimenez, cebolla blanca, pimienta negra, aceite corriente, glucosa, brotes de sakura mix, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'Sí','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Foie Coca with Pedro Ximenez reduction and caramelized onion 1 unit','de'=>'Foie Coca mit Pedro Ximenez Sherry Reduktion und karamellisierten Zwiebeln','es'=>'Coca de Foie con reducción de PX y cebolla caramelizada 1u.',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'coca_langostinos.png',	'Ingredientes'=>'langostinos, cilantro, aguacates grandes, limones, pimienta negra, aceite oliva, pure de mango sicoly, brotes de sakura',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Prawns Coca with avocado tartar and honey‐mango vinaigrette 1 unit','de'=>'Garnelen Coca mit Avocado Tartar und Honig‐Mango‐Vinaigrette','es'=>'Coca de Langostinos con tartar de aguacate y vinagreta de miel y mango 1u',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'setas.png',	'Ingredientes'=>'Setas, ajos pelados, aceite corriente, boletus desidratadas, pimienta negra molida, aceite oliva, champiñones enteros, brotes de sakura mix, perejil',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Sauteed mushrooms with garlic','de'=>'Saute von Pilzen mit jungem Knoblauch','es'=>'Salteado de setas y hongos con ajos tiernos',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'esparragos.png',	'Ingredientes'=>'esparragos trigueros frescos, ajos pelados, aceite corriente, boletus desidratadas, pimienta negra, aceite oliva, tomate parrilla, brotes de sakura mix, perejil, vinagre, almendras fileteadas, harina de trigo,, levadura prensada',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Wild asparagus in tempura with Romesco sauce','de'=>'Grüne Spargel im Teigmantel mit Romesco Sauce','es'=>'Espárragos trigueros en tempura con salsa romescu',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'cazuelita_chori.png',	'Ingredientes'=>'ajos pelados, chistorras, vino blanco, jugo manzana, laurel, aceite oliva, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Chorizo in Cider Casserole with bread sticks','de'=>'Casserole mit Chorizo in Cidre und Brotstückchen','es'=>'Cazuela de chorizo a la sidra con picos de pan',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'calamares.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, calamar grande, laurel, harina de trigo, pan rallado, huevos, aceite corriente, xantana',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Calamari Andalusian style with aioli','de'=>'Tintenfisch nach andalusischer Art mit Aioli','es'=>'Calamares a la andaluza con alioli',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'gambas.png',	'Ingredientes'=>'ajos pelados, aceite oliva, cayena rama, langostinos, perejil, lima',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Shrimp cazuela with garlic sauce and lime juice, flambéeds','de'=>'Cazuela von Garnelen in Knoblauchsoße mit Limettensaft, flambiert','es'=>'Cazuela de gambas al ajillo flambeadas con jugo de lima',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'pulpo.png',	'Ingredientes'=>'papas pais, perejil, sal gruesa, pulpo, laurel, aceite oliva, pimenton',	'allergens'=>['crustáceos'=>'No','moluscos'=>'Sí','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Grilled octopus with smashed potatoes on smoked paprika oil','de'=>'Gegrillter Oktopus mit Kartoffelbrei an geräuchertem Paprika Öl','es'=>'Pulpo a la plancha con patatas rotas al aceite de pimentón ahumado',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            [	'Imagen'=>'merluza.png',	'Ingredientes'=>'ajos pelados, aceite oliva, cayena rama, merluza fresca, perejil, papas',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Battered hake filet with muslin of garlic and rustic potatoes','de'=>'Paniertes Seehechtfilet mit Schaumsauce von Knoblauch und rustikalen Kartoffeln','es'=>'Lomo de merluza rebozado con muselina de ajos y patatas rústicas',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            [	'Imagen'=>'ventresca.png',	'Ingredientes'=>'ajos pelados, aceite oliva, pimientos rojos, lomo atun fresco, papas, pimientos verdes, cebolla grelo, tomate cherry, tomate parrilla, tomate triturado',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Tuna belly filet à point with tomato and escacho of potatoes with saffron oil','de'=>'Bauchfleisch vom Thunfisch auf den Punkt gegart mit Tomaten und Escacho von Kartoffeln mit Safranöl','es'=>'Ventresca de atún en su punto con tomatina y escacho de papas al aceite de azafrán',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            [	'Imagen'=>'bilbaina.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, lomo bacalao, laurel, harina de trigo, papas negras, aceite corriente, aceite oliva, cayena rama',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Cod‐Fillet Bilbao style with black potatoes','de'=>'Kabeljaufilet Bilbaíner Art mit schwarzen Kartoffeln','es'=>'Filete de Bacalao a la Bilbaína con papas negras',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            [	'Imagen'=>'tosta_langostinos.png',	'Ingredientes'=>'ajos pelados, perejil, sal final, langostinos, laurel, tomate parrilla, brnady corriente, chapata tradicion, aceite oliva, cayena rama',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Tiger prawns with garlic and chilli served with bread toasts 5 units','de'=>'Tiger Garnelen mit Knoblauch und Chili serviert mit Toastbrot 5 St.','es'=>'Langostinos tigre con ajo y guindilla servidos con tostas de pan 5u',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            [	'Imagen'=>'entrecot.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, entrecot añojo, pimienta negra, papas arrugadas, brandy corriente, huevos, aceite oliva, ajetes bandeja',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Beefsteak medium with roasted potatoes and aioli','de'=>'Auf den Punkt gebratenes Kalbsteak mit Bratkartoffeln und Aioli','es'=>'Entrecot de Ternera al punto con patatas asadas y Alioli',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'secreto.png',	'Ingredientes'=>'ajos pelados, zanahorias, cebolla blanca, presa de cerdo iberica, pimientos verdes, aceite extra virgen, papas gajos con piel, sal gruesa, pimenton dulce, ajetes bandeja',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Iberian “Secreto” (special pork cut) with seasonal vegetables and paprika spiced potatoes wedges','de'=>'Iberisches Schwein “Secreto” (verstecktes Filet) mit frischem Gemüse der Saison und Kartoffel‐Keile mit Paprika gewürzt','es'=>'Secreto de Cerdo Ibérico con verduras de temporada y patatas gajo al pimentón',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'pato.png',	'Ingredientes'=>'confit pato, orejones de albaricoque, vino tinto, azucar, papas negras, yuca, canela rama, vinagre balsamico, clavo grano',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Duck confit with creamy sauce of dried apricots and sweet wine, on tender potatoes','de'=>'Enten‐confit mit cremiger Sauce von Trockenpfirsich und süßem Wein auf zarten Kartoffeln','es'=>'Confit de pato con salsa cremosa de orejones y vino dulce, sobre papitas tiernas',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'legumeat.png',	'Ingredientes'=>'carne vegetal, perejil, chapata tradicion, leche de soja, cebolla blanca, ajos pelados, gelificante vegetal, sal fina, vino blanco, pimienta negra, tomate natural, papas pais, aceite corriente, aceite oliva',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'Sí',],	'translate'=>['en'=>'Meatballs of Legumeat (meat substitute made with legumes) with homemade tomato sauce and chips','de'=>'Legumeat (Fleischersatz aus Gemüse) Frikadellen mit hausgemachter Tomatensauce und Pommes Frites','es'=>'Albóndigas de Legumeat con salsa casera de tomate y patatas fritas',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'cordero.png',	'Ingredientes'=>'ajetes bandeja, perejil, papas arrugadas, chuletero cordero/solomillo, pimienta negra molida, aceite corriente, vinagre de jerez, salsa soja, ajos pelados, sal maldon, huevos',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Lamb tenderloin with tender garlic, roasted potatoes and aioli','de'=>'Lammfilet mit zartem Knoblauch, gerösteten Kartoffeln und Aioli','es'=>'Solomillo de Cordero con ajos tiernos, patatas asadas y Alioli',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'solomillo.png',	'Ingredientes'=>'solomillo, sal maldon, aceite corriente, aceite oliva, papas pais, vino tinto, glucosa, pimientos rojos, pimientos verdes, ajetes bandeja, clavo grano',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Beef tenderloin in red wine with seasonal vegetables and chips','de'=>'Rinderfilet in Rotwein mit saisonalem Gemüse und Pommes Frites','es'=>'Solomillo de Ternera al vino tinto con verduras de temporada y patatas fritas',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'papaya_mango.png',	'Ingredientes'=>'papayas, mango congelado, sorbete, albahaca, azucar, granadina, gelatina',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Papaya and mango salad with sauce of orange, pomegranate and violet sauce','de'=>'Papaya und Mango‐Salat mit Sauce von Orange ,Granatapfel und Veilchen Sauce','es'=>'Ensalada de papaya y mango con salsa de naranja, granada y gel de violetas',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
            [	'Imagen'=>'mousse.png',	'Ingredientes'=>'manzana reineta, nata liquida, yogur natural, azucar, agua de azahar, lima',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'Sí','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Mousse yogurt with roasted apple and cinnamon','de'=>'Joghurt‐ Mousse mit gebratenem Apfel und Zimt','es'=>'Mousse de yogurt con manzana asada y canela',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
            [	'Imagen'=>'lecheFrita.png',	'Ingredientes'=>'azucar, leche liquida, canela rama, limones, huevos, harina de trigo, canela molida',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Leche frita with lemon sauce','de'=>'Leche frita mit Zitronensauce','es'=>'Leche frita con salsa de limón',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
            [	'Imagen'=>'catalana.png',	'Ingredientes'=>'azucar, leche liquida, canela rama, limones, huevos, canela molida',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Natilla with caramel crust','de'=>'Natilla mit Karamellkruste','es'=>'Natillas con costra de caramelo',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
            [	'Imagen'=>'brocheta.png',	'Ingredientes'=>'papayas, mango congelado, kiwi redondo, melon verde, piña platanos, azucar',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Seasonal fruit skewer caramelized with cane sugar','de'=>'Bratspieß vom Obst der Saison mit karamellisiertem Rohrzucker','es'=>'Brocheta de fruta de temporada caramelizada con azúcar de caña',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
            [	'Imagen'=>'coulant.png',	'Ingredientes'=>'coulant',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'Sí','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Coulant of intense chocolate with red fruit sauce and cream ice cream','de'=>'Coulant aus intensiver Schokolade mit roter Fruchtsauce und Sahneeis','es'=>'Coulant de chocolate intenso con salsa de frutas rojas y helado de nata',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
                                                                        
                                                                        
                                                                        
           // [	'Imagen'=>'ibericos.png',	'Ingredientes'=>'Chorizo ibérico, salchichon ibérico, lomo ibérico, jamón bellota, tomate parrilla, sal maldon, pimienta negra molida, aceite virgen extra, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of Iberian cold cut with rustic bread','de'=>'Auswahl an iberischem Aufschnitt mit rustikalem Brot','es'=>'Selección de embutidos ibéricos con pan rústico',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'','moluscos'=>'','dióxido de azufre y sulfitos'=>'','altramuces'=>'','pescado'=>'','gluten'=>'','apio'=>'','frutos de cáscara'=>'','cacahuetes'=>'','huevos'=>'','soja'=>'','mostaza'=>'','granos de sésamo'=>'',],	'translate'=>['en'=>'','de'=>'','es'=>'Anchoas con sal de ajo y tostadas de pan con tomate en AVOE',],	'foodTypes'=>['Comida vegana'=>'',],	'categories'=>['Entrantes fríos'=>'','Entrantes calientes'=>'','Carnes'=>'','Pescados'=>'','Postres'=>'',],									],
            [	'Imagen'=>'garbanzo.png',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'','moluscos'=>'','dióxido de azufre y sulfitos'=>'','altramuces'=>'','pescado'=>'','gluten'=>'','apio'=>'','frutos de cáscara'=>'','cacahuetes'=>'','huevos'=>'','soja'=>'','mostaza'=>'','granos de sésamo'=>'',],	'translate'=>['en'=>'','de'=>'','es'=>'Cazuela de Fabada Asturiana (Receta Tradicional)',],	'foodTypes'=>['Comida vegana'=>'',],	'categories'=>['Entrantes fríos'=>'','Entrantes calientes'=>'','Carnes'=>'','Pescados'=>'','Postres'=>'',],									],
            [	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'','moluscos'=>'','dióxido de azufre y sulfitos'=>'','altramuces'=>'','pescado'=>'','gluten'=>'','apio'=>'','frutos de cáscara'=>'','cacahuetes'=>'','huevos'=>'','soja'=>'','mostaza'=>'','granos de sésamo'=>'',],	'translate'=>['en'=>'','de'=>'','es'=>'Calandracas (Envueltos fritos de Chorizo fresco y queso en tempura)',],	'foodTypes'=>['Comida vegana'=>'',],	'categories'=>['Entrantes fríos'=>'','Entrantes calientes'=>'','Carnes'=>'','Pescados'=>'','Postres'=>'',],									],
            //[	'Imagen'=>'bilbaina.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, lomo bacalao, laurel, harina de trigo, papas negras, aceite corriente, aceite oliva, cayena rama',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Cod‐Fillet Bilbao style with black potatoes','de'=>'Kabeljaufilet Bilbaíner Art mit schwarzen Kartoffeln','es'=>'Filete de Bacalao a la Bilbaína con papas negras',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
            //[	'Imagen'=>'entrecot.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, entrecot añojo, pimienta negra, papas arrugadas, brandy corriente, huevos, aceite oliva, ajetes bandeja',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Beefsteak medium with roasted potatoes and aioli','de'=>'Auf den Punkt gebratenes Kalbsteak mit Bratkartoffeln und Aioli','es'=>'Lomo de Ternera al punto con patatas asadas y Alioli',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
                                                                        
           // [	'Imagen'=>'ibericos.png',	'Ingredientes'=>'Chorizo ibérico, salchichon ibérico, lomo ibérico, jamón bellota, tomate parrilla, sal maldon, pimienta negra molida, aceite virgen extra, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of Iberian cold cut with rustic bread','de'=>'Auswahl an iberischem Aufschnitt mit rustikalem Brot','es'=>'Selección de embutidos ibéricos con pan rústico',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'pimientos.png',	'Ingredientes'=>'aceite de olvia, sal maldon, pimientos del padron',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Padrón peppers','de'=>'Paprika aus Padrón','es'=>'Pimientos de Padrón',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'salmorejo.png',	'Ingredientes'=>'Tomate parrilla, ajos pelados, aguacates grandes, borraja fresca, agua, aceite oliva, vinagre jerez, sal fina, jamon bellota.',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Salmorejo of organic tomato in EVOO*, slices of Iberian ham and avocado','de'=>'Salmorejo aus Bio‐Tomaten mit NOE*, Scheiben vom iberischen Schinken und Avocado','es'=>'Salmorejo de tomate ecológico con AOVE, lascas de jamón ibérico y aguacate',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'cazuelita_chori.png',	'Ingredientes'=>'ajos pelados, chistorras, vino blanco, jugo manzana, laurel, aceite oliva, chapata tradicion',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Chorizo in Cider Casserole with bread sticks','de'=>'Casserole mit Chorizo in Cidre und Brotstückchen','es'=>'Cazuela de chorizo a la sidra con picos de pan',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'croquetas.png',	'Ingredientes'=>'croqueta de bacalao cebolla caramelizada, croqueta jamon iberico pan crujiente, croquetas bacon y platano koama, croquetas de queso azul nueces, croquetas parmesano y tomate, corquetas de boletus con escamas',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'Sí','gluten'=>'Sí','apio'=>'Sí','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Selection of 6 croquettes (1 unit of each flavour) (Iberian ham with crusty bread, blue cheese and walnuts, Parmesan with tomato, cod with caramelized onions, Boletus with potato flakes and banana with bacon)','de'=>'Zusammenstellung verschiedener Kroketten 6 St. (Iberischer Schinken mit knusprigem Brot, Blauschimmelkäse und Nüssen, Parmesan mit Tomate, Kabeljau mit karamellisierten Zwiebeln, Steinpilz mit Kartoffelflocken und Banane mit Speck)','es'=>'Surtido de croquetas 6u. (1u de cada sabor) (Jamón Ibérico con pan crujiente, Queso azul y nueces, Parmesano con tomate, Bacalao con cebolla caramelizada, Boletus con escamas de patata y Plátano con Bacon',],'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
           // [	'Imagen'=>'tosta_langostinos.png',	'Ingredientes'=>'ajos pelados, perejil, sal final, langostinos, laurel, tomate parrilla, brnady corriente, chapata tradicion, aceite oliva, cayena rama',	'allergens'=>['crustáceos'=>'Sí','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Tiger prawns with garlic and chilli served with bread toasts 5 units','de'=>'Tiger Garnelen mit Knoblauch und Chili serviert mit Toastbrot 5 St.','es'=>'Langostinos tigre con ajo y guindilla servidos con tostas de pan 5u',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'Sí','Postres'=>'No',],									],
           // [	'Imagen'=>'entrecot.png',	'Ingredientes'=>'ajos pelados, perejil, sal fina, entrecot añojo, pimienta negra, papas arrugadas, brandy corriente, huevos, aceite oliva, ajetes bandeja',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'Sí','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Beefsteak medium with roasted potatoes and aioli','de'=>'Auf den Punkt gebratenes Kalbsteak mit Bratkartoffeln und Aioli','es'=>'Lomo de Ternera al punto con patatas asadas y Alioli',],	'foodTypes'=>['Comida vegana'=>'No',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            [	'Imagen'=>'',	'Ingredientes'=>'',	'allergens'=>['crustáceos'=>'','moluscos'=>'','dióxido de azufre y sulfitos'=>'','altramuces'=>'','pescado'=>'','gluten'=>'','apio'=>'','frutos de cáscara'=>'','cacahuetes'=>'','huevos'=>'','soja'=>'','mostaza'=>'','granos de sésamo'=>'',],	'translate'=>['en'=>'','de'=>'','es'=>'Arroz con leche',],	'foodTypes'=>['Comida vegana'=>'',],	'categories'=>['Entrantes fríos'=>'','Entrantes calientes'=>'','Carnes'=>'','Pescados'=>'','Postres'=>'',],									],
                                                                        
            //[	'Imagen'=>'pimientos.png',	'Ingredientes'=>'aceite de olvia, sal maldon, pimientos del padron',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Padrón peppers','de'=>'Paprika aus Padrón','es'=>'Pimientos de Padrón',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
           // [	'Imagen'=>'ens_aguacate_mango.png',	'Ingredientes'=>'pure de maracuya, aguacates grandes, lechuga hoja roble, aceite oliva, aceite oliva virgen extra, vinagre jerez, sal maldon, cebollas rojas, brotes de sakura mix, mango congelado',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Salad of tender sprouts, avocado and mango with passion fruit vinaigrette','de'=>'Salat aus jungen Sprossen, Avocado und Mango mit Passionsfrucht Vinaigrette','es'=>'Ensalada de brotes tiernos, aguacate y mango con vinagreta de maracuyá',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'puerros.png',	'Ingredientes'=>'puerros pais, ajos pelados, perejil, tomate ensalada, aceite oliva, aceite oliva virgen extra ajo, vinagre jerez, sal maldon, pimienta negra grano, brotes de sakura mix, piñones',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'Sí','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Caramelized leeks with fruits trail vanaigrette','de'=>'Karamellisierter Porree mit Vinaigrette aus Trockenfrüchten','es'=>'Puerros caramelizados con vinagreta de frutos secos',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'Sí','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
           // [	'Imagen'=>'setas.png',	'Ingredientes'=>'Setas, ajos pelados, aceite corriente, boletus desidratadas, pimienta negra molida, aceite oliva, champiñones enteros, brotes de sakura mix, perejil',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Sauteed mushrooms with garlic','de'=>'Saute von Pilzen mit jungem Knoblauch','es'=>'Salteado de setas y hongos con ajos tiernos',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
           // [	'Imagen'=>'esparragos.png',	'Ingredientes'=>'esparragos trigueros frescos, ajos pelados, aceite corriente, boletus desidratadas, pimienta negra, aceite oliva, tomate parrilla, brotes de sakura mix, perejil, vinagre, almendras fileteadas, harina de trigo,, levadura prensada',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Wild asparagus in tempura with Romesco sauce','de'=>'Grüne Spargel im Teigmantel mit Romesco Sauce','es'=>'Espárragos trigueros en tempura con salsa romescu',],	'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'Sí','Carnes'=>'No','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'legumeat.png',	'Ingredientes'=>'carne vegetal, perejil, chapata tradicion, leche de soja, cebolla blanca, ajos pelados, gelificante vegetal, sal fina, vino blanco, pimienta negra, tomate natural, papas pais, aceite corriente, aceite oliva',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'Sí','apio'=>'No','frutos de cáscara'=>'Sí','cacahuetes'=>'No','huevos'=>'No','soja'=>'Sí','mostaza'=>'No','granos de sésamo'=>'Sí',],	'translate'=>['en'=>'Meatballs of Legumeat (meat substitute made with legumes) with homemade tomato sauce and chips','de'=>'Legumeat (Fleischersatz aus Gemüse) Frikadellen mit hausgemachter Tomatensauce und Pommes Frites','es'=>'Albóndigas de Legumeat con salsa casera de tomate y patatas fritas',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'Sí','Pescados'=>'No','Postres'=>'No',],									],
            //[	'Imagen'=>'brocheta.png',	'Ingredientes'=>'papayas, mango congelado, kiwi redondo, melon verde, piña platanos, azucar',	'allergens'=>['crustáceos'=>'No','moluscos'=>'No','dióxido de azufre y sulfitos'=>'No','altramuces'=>'No','pescado'=>'No','gluten'=>'No','apio'=>'No','frutos de cáscara'=>'No','cacahuetes'=>'No','huevos'=>'No','soja'=>'No','mostaza'=>'No','granos de sésamo'=>'No',],	'translate'=>['en'=>'Seasonal fruit skewer caramelized with cane sugar','de'=>'Bratspieß vom Obst der Saison mit karamellisiertem Rohrzucker','es'=>'Brocheta de fruta de temporada caramelizada con azúcar de caña',],'foodTypes'=>['Comida vegana'=>'Sí',],	'categories'=>['Entrantes fríos'=>'No','Entrantes calientes'=>'No','Carnes'=>'No','Pescados'=>'No','Postres'=>'Sí',],									],
        ];


        $langs =  DB::table('languages')->get();

        foreach($platos as $plato){


            $dishId = DB::table('dishes')->insertGetId([
                "ingredients"=> $plato['Ingredientes'],
                "image"=> trim($plato['Imagen'], " \t\n\r"),
                "active"=> 1,
            ]);

            foreach ($langs as $lan) {
                DB::table('dishes_translations')->insert(
                    [
                        'id_dish' => $dishId,
                        'id_language' => $lan->id,
                        'name' => $plato['translate'][$lan->code],
                        'description' => ''
                    ]
                );
            }
            
            foreach( $plato['allergens'] as $key => $value){
                if( $value == 'Sí' ){
                    $id_allergen =  DB::table('allergens_translations')->where('name', $key)->first()->id_allergen;
                
                    try{    
                        DB::table('allergens_dishes')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_allergen' => $id_allergen
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($bebida);
                    }
                }
            }

            foreach( $plato['foodTypes'] as $key => $value){
                if( $value == 'Sí' ){
                    
                    $id_food_type = DB::table('food_types_translations')->where('name', $key)->first()->id_food_type ;
                    try{
                        DB::table('dishes_food_types')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_food_type' => $id_food_type,
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($bebida);
                    }
                }
            }

            foreach( $plato['categories'] as $key => $value){
                if( $value == 'Sí' ){
                    print_r($plato['translate']['es']);
                    print_r($value." ".$key);
                    $id_category = DB::table('categories_translations')->where('name', $key)->first()->id_category;
                    try{
                        DB::table('categories_dishes')->insert(
                            [
                                'id_dish' => $dishId,
                                'id_category' => $id_category
                            ]
                        );
                    }catch(Exception $e){
                        echo '
                        ERROR:'.$e->getMessage();
                        print_r($bebida);
                    }
                }
            }

        }

        // $lang =  DB::table('languages')->get();

        // $cant = 80;

        // for ($i = 0 ; $i < $cant ; $i++){
        //     DB::table('dishes')->insert([
        //         'ingredients' => 'ingredients_:' . $i. str_random(15),
        //         'active'=> TRUE,
        //         'image'=>'',
        //     ]);
        // }

        // for ($i = 0 ; $i < $cant ; $i++) {
        //     foreach ($lang as $lan) {
        //         DB::table('dishes_translations')->insert([
        //             [
        //                 'id_dish' => $i+1,
        //                 'id_language' => $lan->id,
        //                 'name' =>$lan->code .'_name' . ($i+1),
        //                 'description' =>$lan->code .' description' . ($i+1)
        //             ]
        //         ]);
        //     }
        // }

    }
}
