<?php

use Illuminate\Database\Seeder;

class WinesWineVarietiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wines_wine_varieties')->truncate();

        $allWines = [
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Montoro',	'VARIEDAD_1'=>'Forastera blanca Gomera',	'VARIEDAD_2'=>'Listan Blanco',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'Moscatel',	'VARIEDAD_5'=>'Pedro Ximenez',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Cumbres de Garajonay',	'VARIEDAD_1'=>'Forastera blanca Gomera',	'VARIEDAD_2'=>'Listan Blanco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Canarius Blanco',	'VARIEDAD_1'=>'Marmajuelo',	'VARIEDAD_2'=>'Listan Blanco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Vijariego Blanco',	'VARIEDAD_1'=>'Vijariego blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera blanco ecológico',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Ensamblaje Blanco',	'VARIEDAD_1'=>'Gual',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'Vijariego blanco',	'VARIEDAD_4'=>'Malvasia aromatica',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Paisaje de las islas "forastera"',	'VARIEDAD_1'=>'Forastera blanca Gomera',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Paisaje de las islas "malvasia y marmajuelo"',	'VARIEDAD_1'=>'Malvasia',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo elaboraciones ancestrales blanco',	'VARIEDAD_1'=>'Gual',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Frontos Blanco Ecologico',	'VARIEDAD_1'=>'Listan blanco ecologico',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Testamento Malvasia Dry',	'VARIEDAD_1'=>'Malvasia aromática',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Testamento Malvasia "fermentado en barrica"',	'VARIEDAD_1'=>'Malvasia aromática',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Altos de tr3vejos blanco',	'VARIEDAD_1'=>'Albillo',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tr3vejos Mountain Wines Listan Blanco & Malvasia',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Moon Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Malvasia aromática',	'VARIEDAD_3'=>'Malvasia aromática',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Albillo Criollo sobre Lias',	'VARIEDAD_1'=>'Albillo Criollo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Los Loros "fermentado en barrica"',	'VARIEDAD_1'=>'Albillo Criollo',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'Gual',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Momentos de Ferrera Blanco',	'VARIEDAD_1'=>'Albillo Criollo',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Artífice Listan Blanco de Canarias "fermentado en barrica"',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Artífice Blanco Vidueños',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'Gual',	'VARIEDAD_4'=>'Albillo Criollo',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marba Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Varietal',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Dominguez Blanco de Uva Tinta',	'VARIEDAD_1'=>'Negramoll de Tacoronte',	'VARIEDAD_2'=>'Malvasia de la punta de Hidalgo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Arautava finca La Habanera',	'VARIEDAD_1'=>'Albillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Suertes del Marqués Trenzado',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Baboso Blanco',	'VARIEDAD_3'=>'Marmajuelo',	'VARIEDAD_4'=>'Albillo',	'VARIEDAD_5'=>'Gual',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Vidonia Vino de Parcela',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Baboso Blanco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Taganán Blanco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'Gual',	'VARIEDAD_4'=>'Vijariego Blanco',	'VARIEDAD_5'=>'Albillo',	'VARIEDAD_6'=>'Forastera',	'VARIEDAD_7'=>'Malvasia',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Taganán Parcela Amogoje',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Marmajuelo',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'Albillo ',	'VARIEDAD_5'=>'Gual',	'VARIEDAD_6'=>'Forastera',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tagalguén Blanco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Albillo Criollo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñarda Blanco Ecologico',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Albillo Criollo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Matías i Torres Albillo',	'VARIEDAD_1'=>'Albillo Criollo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Saaret Malvasia',	'VARIEDAD_1'=>'Malvasia aromática',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La Tablada Llanos Negros ',	'VARIEDAD_1'=>'Gual',	'VARIEDAD_2'=>'Sabro',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Las Machuqueras',	'VARIEDAD_1'=>'Listan Blanco de Canarias',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Los Tabaqueros Llanos Negros',	'VARIEDAD_1'=>'Malvasía aromática',	'VARIEDAD_2'=>'Sabro',	'VARIEDAD_3'=>'Vijariego',	'VARIEDAD_4'=>'Listan Blanco de Canarias',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Blanco Seco',	'VARIEDAD_1'=>'Vijariego blanco',	'VARIEDAD_2'=>'Listan Blanco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Agala Latitud 1318',	'VARIEDAD_1'=>'Vijariego blanco',	'VARIEDAD_2'=>'Albillo Criollo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Volcán de Arena',	'VARIEDAD_1'=>'Verdello',	'VARIEDAD_2'=>'Forastera Blanca',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Volcán Vijariego',	'VARIEDAD_1'=>'Vijariego blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Rubicón Malvasia Seco',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Vega de Yuco Malvasia Seco',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Yaiza Malvasia Seco',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Malvasia Seco',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Grifo Malvasia Seco Colección',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Amalia Malvaia Seco',	'VARIEDAD_1'=>'Malvasia volcánica',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tajinaste Afrutado',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Moon Afrutado',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'Moscatel',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Afrutado',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'Moscatel',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Flor de Chasna Sensación',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marba Afrutado',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'Moscatel',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Saaret Afrutado',	'VARIEDAD_1'=>'Listan blanco',	'VARIEDAD_2'=>'Vijariego Blanco',	'VARIEDAD_3'=>'Baboso blanco',	'VARIEDAD_4'=>'Gual',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Yaiza Afrutado',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'Malvasia volcánica',	'VARIEDAD_3'=>'Diego',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Rubicón Semidulce',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'Malvasia volcánica',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Semidulce',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'Malvasia volcánica',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bibiana Monje',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Rosado Afrutado Semi-seco',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marba rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Varietal',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Frontos Rosado',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Amor, alma & origen Semi-seco',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Yaiza Rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Vega de Yuco Rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Canarius Tinto',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Vijariego Negro',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Tinto Joven',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Arautava Fermentado en Barrica',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Legendario',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Negramoll',	'VARIEDAD_1'=>'Negramoll',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Tintilla',	'VARIEDAD_1'=>'Tintilla',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Ensamblaje Tinto',	'VARIEDAD_1'=>'Baboso negro',	'VARIEDAD_2'=>'Tintilla',	'VARIEDAD_3'=>'Vijariego Negro',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Atlanticum "madurado 6 meses a 18 metros bajo el mar"',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Elaboraciones ancestrales tinto',	'VARIEDAD_1'=>'Tintilla',	'VARIEDAD_2'=>'Baboso Negro',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Frontos Tierra',	'VARIEDAD_1'=>'Listan Prieto',	'VARIEDAD_2'=>'Syrah',	'VARIEDAD_3'=>'Merlot',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Frontos Clásico Baboso',	'VARIEDAD_1'=>'Baboso Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Altos de tr3vejos tinto',	'VARIEDAD_1'=>'Baboso negro',	'VARIEDAD_2'=>'Syrah',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tr3vejos Mountain Wines Baboso Negro',	'VARIEDAD_1'=>'Baboso negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marba Tinto Barrica',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Varietal',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Norte Crianza',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Dominguez Tinto Clásico',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'Tintilla',	'VARIEDAD_4'=>'Listan Blanco',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Capricho',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Castellana',	'VARIEDAD_3'=>'Syrah',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Crater',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'7 Fuentes El Lance',	'VARIEDAD_1'=>'Vijariego Negro',	'VARIEDAD_2'=>'Tintilla',	'VARIEDAD_3'=>'Listan Negro',	'VARIEDAD_4'=>'Baboso Negro',	'VARIEDAD_5'=>'Malvasia Rosada',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tajinaste Vendimia Seleccionada',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Can',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Vijariego',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Ciruelo, Suertes del Marqués. Vino de Parcela',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Chibirique, Suertes del Marqués. Vino de Parcela',	'VARIEDAD_1'=>'Listan Negro en Cordon Trenzado',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Momentos de Ferrera Tinto Crianza',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Artífice Tinto',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Vijariego Negro',	'VARIEDAD_3'=>'Baboso Negro',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Taganán Tinto',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'Mulata ',	'VARIEDAD_4'=>'Moscatel Negra',	'VARIEDAD_5'=>'Listan Gacho',	'VARIEDAD_6'=>'Vijariego Negro',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Taganán Parcela Margalagua',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'Moscatel Negro',	'VARIEDAD_4'=>'Listan Gacho',	'VARIEDAD_5'=>'Vijariego Negro',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Saaret Cuveé',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'Vijariego Negro',	'VARIEDAD_4'=>'Baboso Negro',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Tinto Baboso',	'VARIEDAD_1'=>'Baboso negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tagalguén Tinto Jóven',	'VARIEDAD_1'=>'Listan Prieto',	'VARIEDAD_2'=>'Almuñeco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Los Grillos Llanos Negros',	'VARIEDAD_1'=>'Negramoll',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Matías i Torres Negramoll',	'VARIEDAD_1'=>'Negramoll',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Agala Tinto Joven Altitud 1050',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Tintilla',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Volcán',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Agala Crianza Altitud 1212',	'VARIEDAD_1'=>'Vijariego Negro',	'VARIEDAD_2'=>'Tintilla',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Yaiza Tinto',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Vega de Yuco Tinto',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Maceracion Tradicional',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Grifo Reserva de Familia',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA) Humboldt Tinto Dulce ',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA)Paisaje de las islas "Malvasia Aromática Naturalmente Dulce"',	'VARIEDAD_1'=>'Malvasia aromática',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA)Altos de tr3vejos Blanco Dulce',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA)Teneguía Zeus',	'VARIEDAD_1'=>'Negramoll',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA)Sweet Gold Blanco Dulce',	'VARIEDAD_1'=>'Moscatel de Alejandría',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            //[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Paisaje de las islas',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'NO',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Brut Nature ',	'VARIEDAD_1'=>'Malvasia volcánico',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Brut Nature Rosado',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tr3vejos Brut Nature',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tr3vejos Rosé Brut Nature ',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'SI',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Aurutava Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Fenomenal Sauvignon Blanc',	'VARIEDAD_1'=>'Sauvignon Blanc',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Perro Verde',	'VARIEDAD_1'=>'Verdejo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Gordo del Circo',	'VARIEDAD_1'=>'Verdejo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Perfum Semi-seco',	'VARIEDAD_1'=>'Muscat',	'VARIEDAD_2'=>'Macabeo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Enate 234',	'VARIEDAD_1'=>'Chardonnay',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Predicador Blanco',	'VARIEDAD_1'=>'Viura',	'VARIEDAD_2'=>'Garnacha Blanca',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tarima',	'VARIEDAD_1'=>'Merseguera ',	'VARIEDAD_2'=>'Viognier',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marieta Semi-seco',	'VARIEDAD_1'=>'Albariño',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El jardín de Lucia',	'VARIEDAD_1'=>'Albariño',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La marimorena',	'VARIEDAD_1'=>'Albariño',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'The orange republic',	'VARIEDAD_1'=>'Godello sobre lías',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Mestizaje Blanco "ecológico crianza sobre lías"',	'VARIEDAD_1'=>'Merseguera ',	'VARIEDAD_2'=>'Viognier',	'VARIEDAD_3'=>'Malvasia',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Botani moscatel seco',	'VARIEDAD_1'=>'Moscatel de alejandria',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'8 vírgenes',	'VARIEDAD_1'=>'Palomino fino',	'VARIEDAD_2'=>'Rufete blanco',	'VARIEDAD_3'=>'Moscatel de grano menudo',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Sospechoso blanco ',	'VARIEDAD_1'=>'Airen',	'VARIEDAD_2'=>'Macabeo',	'VARIEDAD_3'=>'Moscatel de grano menudo',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Habla de ti',	'VARIEDAD_1'=>'Sauvignon Blanc',	'VARIEDAD_2'=>'Macabeo',	'VARIEDAD_3'=>'Moscatel de grano menudo',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ferrera afrutado Semi-seco',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñarda ',	'VARIEDAD_1'=>'Negramoll',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Bermejo Ecológico',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La Rosa',	'VARIEDAD_1'=>'Pinot Noir',	'VARIEDAD_2'=>'Garnacha ',	'VARIEDAD_3'=>'Xarel-lo',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Lia de Prado Rey Blush Rosé',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La novia ideal',	'VARIEDAD_1'=>'Bobal',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Sospechoso rosado',	'VARIEDAD_1'=>'Bobal',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Clarete de luna',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Albillo',	'VARIEDAD_3'=>'Garnacha',	'VARIEDAD_4'=>'Verdejo',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Maceración Carbónica',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Agala Tinto Barrica Altitud 1175',	'VARIEDAD_1'=>'baboso negro',	'VARIEDAD_2'=>'Vijariego negro',	'VARIEDAD_3'=>'Tintilla',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Letras Minúsculas ',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Graciano',	'VARIEDAD_3'=>'Garnacha',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La Locomotora',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viuda Negra Nunca Jamás ',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Garnacha',	'VARIEDAD_3'=>'Graciano',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ángeles de Amaren',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Graciano',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Quinta Milú',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Flores de Callejo',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Pruno',	'VARIEDAD_1'=>'Tinto Fino',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Venta las vacas',	'VARIEDAD_1'=>'Tinto fino',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Las retamas del Regajal',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Merlot',	'VARIEDAD_3'=>'Syrah',	'VARIEDAD_4'=>'Cabernet Sauvignon',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Mestizaje Tinto "ecológico fermentado en barrica"',	'VARIEDAD_1'=>'Bobal',	'VARIEDAD_2'=>'Merlot',	'VARIEDAD_3'=>'Cabernet Sauvignon',	'VARIEDAD_4'=>'Garnacha',	'VARIEDAD_5'=>'Tempranillo',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Barbazul',	'VARIEDAD_1'=>'Cabernet Sauvignon',	'VARIEDAD_2'=>'Merlot',	'VARIEDAD_3'=>'Syrah',	'VARIEDAD_4'=>'Tintilla de rota',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La Zorra',	'VARIEDAD_1'=>'Rufete',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'La Zorra Vieja',	'VARIEDAD_1'=>'Rufete',	'VARIEDAD_2'=>'Tinto aragonés',	'VARIEDAD_3'=>'Garnacha',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Sospechoso Tinto',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Tinta de toro',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El marciano',	'VARIEDAD_1'=>'Garnacha',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tarima',	'VARIEDAD_1'=>'Monastrell',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Matsu El Pícaro',	'VARIEDAD_1'=>'Tinta de toro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Románico',	'VARIEDAD_1'=>'Tinta de toro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Habla del Silencio',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'Tempranillo',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Machoman',	'VARIEDAD_1'=>'Monastrell',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'(COPA)Floralis Moscatel Oro',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'MdO Moscato de Ochoa Semi-dulce',	'VARIEDAD_1'=>'Moscatel de grano menudo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            [	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tarima Sparkling',	'VARIEDAD_1'=>'Merseguera ',	'VARIEDAD_2'=>'Macabeo',	'VARIEDAD_3'=>'Moscatel ',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'SI',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tajinaste Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Drago - Blanco Monje',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñatigo Marmajuelo',	'VARIEDAD_1'=>'Marmajuelo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Saaret Forastera Blanca',	'VARIEDAD_1'=>'Forastera Blanca Gomera',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Frontos Blanco Clásico',	'VARIEDAD_1'=>'Marmajuelo',	'VARIEDAD_2'=>'Verdello',	'VARIEDAD_3'=>'Albillo',	'VARIEDAD_4'=>'Malvasia',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Flor de Chasna Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Brumas de Ayosa Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco de Altura',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Contiempo Vidueño',	'VARIEDAD_1'=>'Marmajuelo',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'Moscatel',	'VARIEDAD_4'=>'Verdello',	'VARIEDAD_5'=>'Gual',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tagara Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Norte Blanco Seco',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Teneguía La Gota ',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Vijariego',	'VARIEDAD_3'=>'Albillo',	'VARIEDAD_4'=>'Negramoll',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tagara afrutado',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Brumas de Ayosa Blanco Afrutado',	'VARIEDAD_1'=>'moscatel de alejandria',	'VARIEDAD_2'=>'listan blanco',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Flor de Chasna Afrutado',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Grifo "el afrutado"',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Diego',	'VARIEDAD_3'=>'Moscatel',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Afrutado',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'vijariego blanco ',	'VARIEDAD_3'=>'Moscatel de Alejandría',	'VARIEDAD_4'=>'Malvasia',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Sol ',	'VARIEDAD_1'=>'Garnacha blanca',	'VARIEDAD_2'=>'Parellada',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Esmeralda',	'VARIEDAD_1'=>'Moscatel',	'VARIEDAD_2'=>'Gewürztraminer',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Gran Feudo Chardonay ',	'VARIEDAD_1'=>'Chardonnay',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Gran Viña Sol',	'VARIEDAD_1'=>'Chardonnay',	'VARIEDAD_2'=>'Parellada',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñas del Vero',	'VARIEDAD_1'=>'Macabeo',	'VARIEDAD_2'=>'Chardonnay',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Carramimbre',	'VARIEDAD_1'=>'Verdejo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Palacio de Bornos Sauvignon Blanc',	'VARIEDAD_1'=>'Sauvignon Blanc',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marqués de Cáceres',	'VARIEDAD_1'=>'Viura',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ostatu',	'VARIEDAD_1'=>'Viura',	'VARIEDAD_2'=>'Malvasia',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Monje Tradicional',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Listan Negro',	'VARIEDAD_3'=>'Negramoll',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tajinaste Tinto Roble',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Frontera Tradicional',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Flor de Chasna 4 meses barrica',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Norte Tradicional',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Brezal',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Negramoll',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Ancón Tinto Jóven',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Contiempo Vendimia Seleccionada',	'VARIEDAD_1'=>'Syrah',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Tajinaste Tradicional',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Siete fuentes',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'Tintilla',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'El Grifo ',	'VARIEDAD_1'=>'Listan Negro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Ostatu',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Viura',	'VARIEDAD_3'=>'Graciano',	'VARIEDAD_4'=>'Mazuelo',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Marqués de Cáceres Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Garnacha tinta',	'VARIEDAD_3'=>'Graciano',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Salceda Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Mazuelo',	'VARIEDAD_3'=>'Graciano',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Campillo Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Muga Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Garnacha',	'VARIEDAD_3'=>'Mazuelo',	'VARIEDAD_4'=>'Graciano',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Raiza Reserva',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Señorio de Ondarre Reserva',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Mazuelo',	'VARIEDAD_3'=>'Garnacha',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viña Ardanza Reserva',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Garnacha',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Píxide',	'VARIEDAD_1'=>'Tinto Fino',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Canta Perdices',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Pradorey Roble',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'Merlot',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Carramimbre Roble',	'VARIEDAD_1'=>'Tinta del pais',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Los Camptos de Torremilanos',	'VARIEDAD_1'=>'Listan Blanco',	'VARIEDAD_2'=>'Tempranillo',	'VARIEDAD_3'=>'Merlot',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Protos Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Torremilanos Reserva',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Honoro Vera Garnacha',	'VARIEDAD_1'=>'Garnacha',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Honoro Vera Monastrell Ecologico',	'VARIEDAD_1'=>'Monastrell ecologico',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Elías Mora Roble',	'VARIEDAD_1'=>'Tinta de Toro',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Habla la Tierra',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Viñas del Vero Roble',	'VARIEDAD_1'=>'Cabernet Sauvignon',	'VARIEDAD_2'=>'Merlot',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Gran Feudo Crianza',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'Merlot',	'VARIEDAD_4'=>'Garnacha',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Gran Feudo Reserva',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'Cabernet Sauvignon',	'VARIEDAD_3'=>'Merlot',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Santa Digna Cabernet Sauvignon',	'VARIEDAD_1'=>'Cabernet Sauvignon',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Santa Digna Merlot',	'VARIEDAD_1'=>'Merlot',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Santa Digna Carmenere',	'VARIEDAD_1'=>'Carmenere',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Pérez Cruz Reserva',	'VARIEDAD_1'=>'Cabernet Sauvignon',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Alta Visita Premium Malbec',	'VARIEDAD_1'=>'Malbec',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Koonunga Hill',	'VARIEDAD_1'=>'Shiraz Cabernet',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Blanc de Blancs Raventós i Blanc',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'De Nir Rosé Raventós i Blanc',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Möet & Chandon Impérial Brut',	'VARIEDAD_1'=>'Tempranillo',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Möet & Chandon Impérial Brut Rosé',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Veuve Clicquot Brut Yellow Label',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Veuve Clicquot Rosé Yellow Label ',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
            ////[	'TIPO DE BEBIDA'=>'Vino',	'Nombre de la bebida'=>'Dom Pérignon',	'VARIEDAD_1'=>'',	'VARIEDAD_2'=>'',	'VARIEDAD_3'=>'',	'VARIEDAD_4'=>'',	'VARIEDAD_5'=>'',	'VARIEDAD_6'=>'',	'VARIEDAD_7'=>'',	'GARA'=>'NO',	'TASCA'=>'NO',	],
        ];

        //    php artisan db:seed --class=WinesWineVarietiesTableSeeder

        // $wines =  DB::table('wines')->get();

        $langs =  DB::table('languages')->get();

         foreach ($allWines as $wine) {

             if(DB::table('wines')->where('name',$wine['Nombre de la bebida'])->first()){
                $wineId = DB::table('wines')->where('name',$wine['Nombre de la bebida'])->first()->id;

                 for($i=1;$i<8;$i++){
                     if(trim(@$wine['VARIEDAD_'.$i])!=''){
                         $id_variety=NULL;
                         if(App\WineVarietyTranslation::where('name',$wine['VARIEDAD_'.$i])->first()){
                             $id_variety=App\WineVarietyTranslation::where('name',$wine['VARIEDAD_'.$i])->first()->id_wine_variety;
                         }else{
                             echo 'creamos la nueva variedad '.$wine['VARIEDAD_'.$i]. PHP_EOL;
                             $id_variety = DB::table('wine_varieties')->insertGetId([
                                 'id' => NULL
                             ]);
                             foreach ($langs as $lan) {
                                 DB::table('wine_variety_translations')->insert([
                                     [
                                         'id_wine_variety' => $id_variety,
                                         'id_language' => $lan->id,
                                         'name' => $wine['VARIEDAD_'.$i]
                                     ]
                                 ]);
                             }
                         }
                         try{
                             DB::table('wines_wine_varieties')->insert([
                                 'id_wine'=>$wineId,
                                 'id_wine_variety'=>$id_variety
                             ]);
                         }catch(Exception $e){
                             echo 'ERROR:'.$e->getMessage(). PHP_EOL;
                             print_r($wine);
                         }
                     }
                 }
             }else{
                 echo "NO ESTA : ". ($wine['Nombre de la bebida']) . PHP_EOL;
             }



        //     $wine_varieties = rand(0 ,1 );
        //     $varieties = DB::table('wine_varieties')->inRandomOrder()->take($wine_varieties)->get();

        //     for ($j= 0 ; $j <= $wine_varieties ;$j++){
        //         try{
        //             DB::table('wines_wine_varieties')->insert([
        //                 'id_wine_variety' => $varieties[$j]->id ,
        //                 'id_wine' => $wine->id
        //             ]);
        //         }catch( Exception $exception){

        //         }
        //     }

         }

    }
}
